feat(packages/python-sentencepiece-gfx1151): bundle sentencepiece core by default

diff --git a/packages/python-sentencepiece-gfx1151/PKGBUILD b/packages/python-sentencepiece-gfx1151/PKGBUILD
--- a/packages/python-sentencepiece-gfx1151/PKGBUILD
+++ b/packages/python-sentencepiece-gfx1151/PKGBUILD
@@ -6,20 +6,46 @@
 
 pkgname=python-sentencepiece-gfx1151
 pkgver=0.2.1.r8.d20260317.gad42886
-pkgrel=1
+pkgrel=2
 pkgdesc='Python wrapper for SentencePiece rebuilt for Strix Halo gfx1151'
 arch=('x86_64')
 url=https://github.com/google/sentencepiece
 license=(Apache-2.0)
-depends=(gcc-libs glibc python-gfx1151 sentencepiece)
+depends=(gcc-libs glibc python-gfx1151)
 makedepends=(cmake ninja python-build python-installer python-wheel rocm-llvm-gfx1151)
 optdepends=(python-protobuf)
 options=()
 provides=(python-sentencepiece)
 conflicts=(python-sentencepiece)
 replaces=()
-source=(https://files.pythonhosted.org/packages/source/s/sentencepiece/sentencepiece-0.2.1.tar.gz)
-sha256sums=(SKIP)
+source=(https://files.pythonhosted.org/packages/source/s/sentencepiece/sentencepiece-0.2.1.tar.gz 0001-bundle-sentencepiece-by-default.patch)
+sha256sums=(SKIP SKIP)
+
+_apply_patch_if_needed() {
+  local _patch_name="$1"
+  local _patch=""
+
+  if [[ -f "${srcdir}/${_patch_name}" ]]; then
+    _patch="${srcdir}/${_patch_name}"
+  elif [[ -f "${startdir}/${_patch_name}" ]]; then
+    _patch="${startdir}/${_patch_name}"
+  else
+    printf 'missing patch file: %s\n' "${_patch_name}" >&2
+    return 1
+  fi
+
+  if patch --dry-run -R -Np1 -i "${_patch}" >/dev/null 2>&1; then
+    return 0
+  fi
+
+  patch -Np1 -i "${_patch}"
+}
+
+prepare() {
+  cd "$srcdir/sentencepiece-0.2.1"
+
+  _apply_patch_if_needed "0001-bundle-sentencepiece-by-default.patch"
+}
 
 build() {
   cd "$srcdir/sentencepiece-0.2.1"
